# Enable examples to find the library headers
include_directories(${CMAKE_SOURCE_DIR}/include)

# Add subdirectories
add_subdirectory(BasicExample)
add_subdirectory(CascadeDemo)
add_subdirectory(SignalBoard)
add_subdirectory(ToggleDemo)
add_subdirectory(UIShowcase)

 add_subdirectory(ScreenShareDemo)
 add_subdirectory(MonitorApp)
 add_subdirectory(CodeEditorDemo)
 add_subdirectory(RichTextEditorDemo)
 add_subdirectory(ColorPickerDemo)
 add_subdirectory(ScrollPanelDemo)
 add_subdirectory(EditableListDemo)